name: intl_message
description: Parses and formats ICU Message strings. Formats strings in multiple languages.
version: 0.3.2
homepage: https://github.com/appsup-dart/intl_message
funding:
 - https://github.com/sponsors/rbellens

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl: '>=0.17.0 <0.19.0'
  petitparser: ^5.0.0
  expressions: ^0.2.0

dev_dependencies:
  test: ^1.0.0
  pedantic: ^1.11.0
